nuxt/scripts

src/registry.ts
When I accessed the Youtube Player page using the following flow line, a 404 error was returned.
- 🆖 `/` page: Click Youtube Logo
- 🆖 `/scripts` page: Click `Youtube Iframe` content
- 🆗 `scripts` page, side menu: Click `Content > Youtube Player`
When we investigated the cause, we found that it failed in the case of **Youtube Iframe**.
=> docs: fix links to Youtube Player

src/module.ts, src/registry.ts
Currently using build-time types prevent having good strict types in module integrations.
This is due to @nuxt/scripts importing `#nuxt-scripts` alias in type declaration which typescript cannot be aware of, except if the module author extends its tsconfig from a playground tsconfig (but this brings other issues)
=> fix: don't use aliases in build-time files

package.json
This PR adds `#nuxt-scripts-validator` to `externals`
=> build: add #nuxt-scripts-validator to externals

src/runtime/components/ScriptVimeoPlayer.vue, src/runtime/registry/vimeo-player.ts
Looks like there can be some issues when importing vimeo player. This PR moves vimeo__player imports directly to `<reference>`
=> fix(vimeo): vimeo player to reference types

src/runtime/components/ScriptGoogleMaps.vue, src/runtime/registry/google-maps.ts
seems like we need to use `typeof window['namespace']` to correctly type the api types when using namespaces
=> fix(gmap): fix gmap types being overriden

src/runtime/registry/vimeo-player.ts, src/runtime/utils.ts
Currently building nuxt-scripts makes all registry scripts function type return `any` in declaration files. Forcing the return type of `useRgistryScript` fix this issue
fix #72
=> fix: force useRegistry return type

src/runtime/components/ScriptVimeoPlayer.vue
The user does not always have to provide an ID, but what if a link comes from the API?
=> fix(vimeo): support `url` prop

src/runtime/types.ts
This PR fix the return type of `scriptBundling`
=> fix: correct scriptBundling return type

docs/content/scripts/content/google-maps.md
Tiny PR to explain the trade-off if you use the static maps API (more up front if users engage, less if they don't). @harlan-zw This was my understanding from your comment - let me know if it's not right.
=> docs: add more detail to billing docs

eslint.config.js, eslint.config.mjs, package.json, pnpm-lock.yaml, src/runtime/components/ScriptVimeoPlayer.vue, src/runtime/registry/google-maps.ts, test/unit/transform.test.ts
Repositories in Nuxt oranization are migrating to use [Nuxt ESLint](https://eslint.nuxt.com/).
Therefore, this repository has also been migrated to use `@nuxt/eslint-config` instead of `@antfu/eslint-config`.
`node/prefer-global/process` and `node/prefer-global/buffer` are rules provided by `eslint-plugin-n`, and were not provided by default in `@nuxt/eslint-config`.
As before, if necessary, you can configure all `eslint-plugin-n` rules configured in `@antfu/eslint-config` in a separate PR. 👍 
I thought that this rules should be implemented after receiving @harlan-zw 's opinion, so it has not been addressed in this PR.
=> chore: migrate to Nuxt ESLint

docs/content/scripts/marketing/clarity.md, docs/pages/index.vue, docs/pages/scripts.vue, playground/pages/third-parties/clarity/nuxt-scripts.vue, src/registry.ts, src/runtime/registry/clarity.ts
https://clarity.microsoft.com/
Global
```ts
export default defineNuxtConfig({
scripts: {
registry: {
clarity: {
id: 'YOUR_ID'
}
}
}
})
```
API
```ts
const { clarity } = useScriptClarity({
id: 'YOUR_ID'
})
clarity("identify", "custom-id", "custom-session-id", "custom-page-id", "friendly-name")	
```
=> feat: clarity

docs/package.json, playground/package.json, pnpm-lock.yaml
It's about package management that I was talking about in this comment.
- https://github.com/nuxt/scripts/pull/86#issuecomment-2156449546
=> chore(monorepo): put deps in root

README.md
=> docs(readme): fix links in `Next Steps`

docs/components/content/GoogleMapsDemo.vue, docs/content/scripts/content/google-maps.md, playground/scripts/myCustomScript.ts, src/runtime/components/ScriptGoogleMaps.vue, src/runtime/components/ScriptVimeoPlayer.vue, src/runtime/components/ScriptYouTubePlayer.vue, src/runtime/registry/intercom.ts
`import type { foo }` and `import { type foo }` were mixed, so I refactored it to `import type { foo }`.
- related: https://nuxt.com/blog/v3-8#type-import-changes
Refactoring after the official release is hard, so I fixed it first.
=> refactor: refactor `import { type foo }` to `import type { foo }`

eslint.config.js, package.json, pnpm-lock.yaml
related #86 .
Added `eslint-plguin-n` written in Note #86 .
Also, ESLint updated.
=> chore: add `eslint-plugin-n` to ESLint rules

docs/components/LogoScroller.vue, docs/components/OgImage/Docs.vue, docs/components/OgImage/Home.vue, docs/content/docs/1.getting-started/3.confetti-tutorial.md, docs/content/docs/1.guides/1.registry-scripts.md, docs/content/docs/1.guides/3.consent.md, docs/content/docs/1.guides/4.global.md, docs/content/docs/3.api/3.use-consent-script-trigger.md, docs/content/docs/3.api/3.use-element-script-trigger.md, docs/content/docs/3.api/4.use-analytics-page-event.md, docs/content/scripts/analytics/cloudflare-web-analytics.md, docs/content/scripts/analytics/google-analytics.md, docs/content/scripts/analytics/matomo-analytics.md, docs/content/scripts/analytics/plausible-analytics.md, docs/content/scripts/content/google-maps.md, docs/content/scripts/marketing/clarity.md, docs/content/scripts/marketing/hotjar.md, docs/content/scripts/marketing/intercom.md, docs/content/scripts/payments/lemon-squeezy.md, docs/content/scripts/payments/stripe.md, docs/content/scripts/tracking/google-tag-manager.md, docs/content/scripts/tracking/meta-pixel.md, docs/content/scripts/tracking/segment.md, docs/content/scripts/tracking/x-pixel.md
Since `<script setup lang="ts">` and `<script lang="ts" setup>` were mixed, we unified them to `<script setup lang="ts">`.
=> docs: refactor `script setup lang="ts"`

src/runtime/types.ts, src/tpc/google-analytics.ts, src/tpc/google-tag-manager.ts, test/types/types.test-d.ts, tsconfig.json
This PR fix the module registry type generation since nuxt-module-builder 0.8. It simply write the generated files and fix some imports
=> chore: fix module option registry type generation

src/tpc/google-analytics.ts, src/tpc/google-tag-manager.ts, src/tpc/utils.ts, test/unit/tpc.test.ts
Small refactor PR to remove `augmentWindowTypes` from the tpc utils as we'll likely always augment it. 
Included in #113
=> refactor(tpc): remove augmentWindowTypes

package.json
related nuxt-modules/sitemap#303
Drop `postinstall` considering that it will also affect Nuxt Scripts.
`postinstall` is added in this commit: 735fdbd9be6792d64221134a91a1f45a819c3179
=> chore: drop `postinstall`

src/module.ts, src/tpc/google-analytics.ts, src/tpc/google-tag-manager.ts
This PR push tpc composables into the registry array instead of using the hook. Using the hook would make @nuxt/scritps consider tpc composables as new scripts
=> fix(tpc): directly push tpc composables into registry

src/tpc/utils.ts, test/unit/tpc.test.ts
fix #135
hey this PR fix an issue with `third-party-capital`. Since tpc composables are generated in .nuxt, we need to resolve the path of third-party-capital from @nuxt/script within the users node_modules as users won't install it.
=> fix(tpc): use mlly to resolve third-party-capital

docs/pages/index.vue
The old url was pointing to `/guides`, but it actually resides in `/getting-started`
=> doc: typo for js-confetti getting-started guide

docs/content/docs/1.guides/1.registry-scripts.md, playground/pages/third-parties/google-analytics/multiple.vue, src/runtime/registry/clarity.ts, src/runtime/registry/cloudflare-web-analytics.ts, src/runtime/registry/crisp.ts, src/runtime/registry/fathom-analytics.ts, src/runtime/registry/google-adsense.ts, src/runtime/registry/google-maps.ts, src/runtime/registry/hotjar.ts, src/runtime/registry/intercom.ts, src/runtime/registry/lemon-squeezy.ts, src/runtime/registry/matomo-analytics.ts, src/runtime/registry/meta-pixel.ts, src/runtime/registry/npm.ts, src/runtime/registry/plausible-analytics.ts, src/runtime/registry/segment.ts, src/runtime/registry/stripe.ts, src/runtime/registry/vimeo-player.ts, src/runtime/registry/x-pixel.ts, src/runtime/registry/youtube-player.ts, src/runtime/types.ts, src/tpc/utils.ts
Fixes #97
You may have a setup where you need to load the same registry script multiple times
using different configuration. 
By default, they will be deduped and only loaded once, to load multiple instances of the same script, you can provide a unique `key` to the script.
```ts
const { gtag, $script } = useScriptGoogleAnalytics({
id: 'G-TR58L0EF8P',
})
const { gtag: gtag2, $script: $script2 } = useScriptGoogleAnalytics({
// without a key the first script instance will be returned
key: 'gtag2',
id: 'G-1234567890',
})
```
It's important to note that when modifying the key, any environment variables you're using will break.
For example, with `gtag2` as the key, you'd need to provide runtime config as following:
```ts
export default defineNuxtConfig({
runtimeConfig: {
public: {
scripts: { …
```
=> feat: support manual script deduping

docs/content/docs/1.getting-started/3.confetti-tutorial.md
I've tried to go through the tutorial and am stuck with typings because some code snippets were wrong.
=> docs: broken tutorial, put some `use` into `scriptOptions`

scripts/generateTpcScripts.ts, scripts/tsconfig.json
This PR adds a tsconfig and remove ts-expect-error to stop vscode warnings
=> chore: add tsconfig to scripts and remove unused ts-expect-error

docs/content/docs/1.getting-started/3.confetti-tutorial.md
=> docs: fix typo in js-confetti guide

docs/content/scripts/analytics/google-analytics.md, docs/content/scripts/tracking/google-tag-manager.md
=> docs: mention third-party-capital and aurora for tpc composables

src/runtime/components/ScriptYouTubePlayer.vue
The ScriptYouTubePlayer component documentation mentions a default slot that can be used to display content that will always be visible but it is not present in the component. This PR aims to fix that.
=> fix(ScriptYouTubePlayer): missing default slot

package.json, pnpm-lock.yaml, scripts/generateTpcScripts.ts, scripts/utils.ts, src/runtime/registry/google-analytics.ts, src/runtime/registry/google-tag-manager.ts
fix #184 
This PR updates TPC and fix GA. The issue is caused by the gtag function.
This is probably an undocumented spec within GA. Seems like GA (unlike GTM) **needs** to received arguments in order to collect data.
=> fix(tpc): update TPC and fix GA

client/bootstrap.ts
This change corrects the import path for `DEVTOOLS_UI_LOCAL_PORT` by referencing it from the constants file.
=> chore: update import path for devtools port

docs/content/scripts/content/vimeo-player.md, playground/pages/third-parties/vimeo/nuxt-scripts.vue, src/runtime/components/ScriptVimeoPlayer.vue
Vimeo player is not working because the prop merging is buggy. To solve this, the easiest way that is future-proof is to add the `vimeoOptions` to the props.
For convenience and to lessen the breaking changes, we accept an `id` or an `url` top level as well.
While modifying this, we also prefer automatic height based on the parent container.
⚠️ This is a breaking change for anyone using the vimeo options as root level props and may style differently.
=> fix(vimeo)!: broken player, refactor props

playground/pages/features/on-nuxt-ready.vue, playground/pages/npm/js-confetti.vue, playground/pages/third-parties/clarity/nuxt-scripts.vue, playground/pages/third-parties/cloudflare-web-analytics/nuxt-scripts.vue, playground/pages/third-parties/fathom-analytics.vue, playground/pages/third-parties/google-adsense/unhead.vue, playground/pages/third-parties/google-analytics/multiple.vue, playground/pages/third-parties/google-analytics/nuxt-scripts.vue, playground/pages/third-parties/google-tag-manager.vue, playground/pages/third-parties/hotjar.vue, playground/pages/third-parties/intercom/use-script.vue, playground/pages/third-parties/matomo-analytics.vue, playground/pages/third-parties/meta-pixel.vue, playground/pages/third-parties/plausible-analytics.vue, playground/pages/third-parties/segment.vue, playground/pages/third-parties/x-pixel/nuxt-scripts.vue
Relate to this unhead [PR](https://github.com/unjs/unhead/pull/379#issue-2470480475) and this [tag](https://github.com/nuxt/scripts/blob/main/src/runtime/composables/useScript.ts#L19-L21)
Reduce the deprecated way of using script instance functions in the playground domain.
=> refactor(playground): avoid deprecated useScript api

docs/content/docs/1.getting-started/2.installation.md, docs/content/docs/1.getting-started/3.confetti-tutorial.md
- The text `Script Loading` points to a invalid link, and I guess, author meant to point to [this page](https://scripts.nuxt.com/docs/guides/script-triggers).
- The text `proxied functions` should point to [this page](https://scripts.nuxt.com/docs/guides/key-concepts#understanding-proxied-functions)
=> chore(docs): fix incorrect links

docs/content/docs/3.api/3.use-script-trigger-element.md, src/runtime/components/ScriptCarbonAds.vue, src/runtime/components/ScriptCrisp.vue, src/runtime/components/ScriptGoogleAdsense.vue, src/runtime/components/ScriptGoogleMaps.vue, src/runtime/components/ScriptIntercom.vue, src/runtime/components/ScriptLemonSqueezy.vue, src/runtime/components/ScriptStripePricingTable.vue, src/runtime/components/ScriptVimeoPlayer.vue, src/runtime/components/ScriptYouTubePlayer.vue, src/runtime/composables/useScriptTriggerElement.ts
https://github.com/nuxt/scripts/issues/205
When registering a trigger that depends on user input, such as `mousedown`, it's possible that the user will interact with the element before the hydration process is complete. 
In this case, the event listener will not be attached to the element, and the script will not be loaded.
To ensure this is handled correctly you should bind the `ssrAttrs` value to the element you're attaching events to. Note that you should verify
that a promise is returned from the function before using the `ssrAttrs` value.
```vue
<script setup lang="ts">
import { ref, useScriptTriggerElement } from '#imports'
const el = ref<HTMLElement>()
const trigger = useScriptTriggerElement({
trigger: 'mousedown',
el,
})
const elAttrs = computed(() => {
return {
...(trigger …
```
=> feat(useScriptTriggerElement): pre-hydration event triggers

src/assets.ts
fix https://github.com/nuxt/scripts/issues/233
This PR stops the build process if a script download fails
=> fix(bundling): throw error if download fails 

src/runtime/components/ScriptGoogleAdsense.vue
Resolves #247
Removed the default ad format, allowing for fixed-size ad units
=> fix(adsense)!: remove default `data-ad-format`

docs/content/docs/3.api/6.nuxt-hooks.md
docs: update script:registry hook example
Resolves #267 
The example in the docs on how to extend registry scripts via `scripts:registry` is not working. I updated it with a working example.
see #267
=> docs: update scripts:registry hook example

src/runtime/components/ScriptYouTubePlayer.vue
Removed the backticks that makes the "height" prop invalid for CSS.
=> fix: :bug: Fixed "height" css style property

src/runtime/components/ScriptGoogleAdsense.vue
Allow multiple ad slots to be pushed in production, but call once only in dev  because HMR triggers new ad to be pushed each time
=> fix(adsense): push ad slot once only on dev

docs/content/docs/1.guides/1.registry-scripts.md
The description of disabling nuxt scripts in development provided the information about using `mock`. The snippet on the other hand did not use `mock`. This was introduced in 253085d1c79403d65d17f50f48d4874e0a714448.
=> docs: fix docs for disabling scripts in development

src/runtime/types.ts, src/runtime/utils.ts
@harlan-zw following the discord discussion, this could be a first solution for TPC V3. This would allow to have typesafety but without runtime validation so we don't have to know how TPC or any other type is defined but passing it as a Type Parameter would be enough to warn devs that something is wrong
cc @flashdesignory
=> fix: optional Valibot schema

src/module.ts
Fix autocompletion when using global scripts (proxy, onLoaded, ...)
=> fix: `nuxtApp.$scripts` types

docs/content/docs/1.guides/1.registry-scripts.md
I am new to nuxt script, and after reading the docs I still have no idea how to config a registry script with env. There were like 3 different versions of key names for a same example
=> docs: fix inconsistent example env keys

src/runtime/components/ScriptVimeoPlayer.vue, src/runtime/components/ScriptYouTubePlayer.vue
Currently, the media players have a fixed width, which makes them non-responsive on mobile devices. This breaks the view completely, as they overflow way off screen. By making the width automatic, it can be more responsive to small screen sizes and keep the structure of the page.
=> fix(YoutubePlayer,VimeoPlayer)!: auto width for responsive design on mobile devices

docs/content/docs/1.guides/1.script-triggers.md
Improve incorrect example of `useScriptTriggerElement` so it includes the specifically named property `el` as such
This PR corrects a mistake in the documentation that incorrectly shows the possibility of providing the function `useScriptTriggerElement` with a property called `somethingEl`, while that should be called `el`.
=> docs: Improve incorrect example of using useScriptTriggerElement

package.json, pnpm-lock.yaml
This PR fix the current issue with nuxt-module-builder/rollup not being able to properly type consola due to multiple versions of consola being present in the lockfile
=> build: set a resolution for consola

src/runtime/registry/npm.ts
Resolves the [TODO](https://github.com/nuxt/scripts/blob/b1e4297d9532b9e5d7b5262353976f4cfdb75419/src/runtime/registry/npm.ts#L16)
Implement the TODO for multiple providers, as I also believe it is necessary.
cmiiw: it seems the optional schema `type` is not being used. So, I would suggest using a `provider` for clearer meaning.
The default provider is unpkg.
=> feat(useScriptNpm): support multiple providers with validation

docs/content/scripts/analytics/umami-analytics.md, src/registry.ts, src/runtime/registry/umami-analytics.ts, src/runtime/types.ts
add Umami Analytics to registry and docs
=> feat: add umami analytics to registry

src/runtime/components/ScriptGoogleMaps.vue, src/runtime/components/ScriptVimeoPlayer.vue, src/runtime/components/ScriptYouTubePlayer.vue
Since the type dependencies were dropped in commit f54552654d047bf33eeef2a158819b78cdd60518, typechecking in projects that rely on Nuxt scripts is failing.
To get things moving again, I’ve added @ts-nocheck to ignore the type errors for now. I know this isn’t a great solution and can hide real issues, but it’s the best workaround I could come up with at the moment.
=> fix: expect type error for optional type deps

docs/content/scripts/content/google-maps.md
Fixes a typo in the Google Maps section of docs. Package name was missing an s.
=> docs(GoogleMaps): fix typo in package name

docs/content/docs/1.guides/0.key-concepts.md
Resolves #304  : Some users expected `async` to be applied by default, leading to confusion. This update makes the behavior explicit.
- Updated documentation to clarify that `async` is not applied by default   because `defer` is used.  
- Added a note explaining how to explicitly enable `async` by disabling `defer`.  
- Improved readability of default script attributes section.
=> docs: clarify async behavior and default script attributes

docs/content/scripts/ads/google-adsense.md, playground/pages/index.vue, src/runtime/registry/google-adsense.ts
This PR improves the Google Adsense registry script by simplifying initialization, fixing auto ads issues, and ensuring a cleaner implementation.
No
- **Removed** dynamic `client` query param from `adsbygoogle.js` URL (redundant and unnecessary).  
- **Improved** script injection logic to ensure proper `useHead` usage.  
- **Fixed** auto ads initialization issue (`enable_page_level_ads` now properly handled).  
- **Standardized** TypeScript typings and comments for better maintainability.  
- **Ensured** compatibility with future registry script updates.
=> fix(googleAdsense): improve initialization & auto ads handling

docs/content/scripts/tracking/google-tag-manager.md, playground/pages/third-parties/google-tag-manager.vue, src/runtime/registry/google-analytics.ts, src/runtime/registry/google-tag-manager.ts
resolve #243
This PR improves GTM by adding a new callback to allow users to push anything into the datalayer before we push gtm.start . This way, users will be able to correctly set the consent mode
=> feat(gtm): add onBeforeGtmStart

client/components/OCodeBlock.vue, client/composables/shiki.ts, package.json
|           |  gziped  | unpacked |
| :-------: | :------: | :------: |
| original  |  1.8 MB  | 9.7 MB  |
| optimized | 253.7 kB |  879.9 kB  |
- Use [fine grained bundle](https://shiki.style/guide/bundles#fine-grained-bundle) to only bundle needed languages and themes.
- Use [Javascript RegExp Engine](https://shiki.style/guide/regex-engines#javascript-regexp-engine).
=> perf: only bundle needed shiki langs and themes

docs/package.json, pnpm-lock.yaml
aims to resolve docs deploy + unblock CI by adding ohash v1 manually - but only in docs (which ui-pro still depends on) - a similar strategy [worked for nuxt/fonts](https://github.com/nuxt/fonts/pull/558)
docs are still failing due to unenv hoisting
=> chore: add ohash v1 to docs deploy

src/module.ts
We need to resolve @unhead/vue from the module location. 
A .catch has been added in case `readPackageJSON` wasn't able to find `@unhead/vue`.
=> fix: resolve @unhead/vue from module and catch if fails

src/runtime/types.ts
Resolves https://github.com/nuxt/scripts/issues/419
I'm new to OSS contributions, so I appreciate any feedback or corrections. 🙏
The `@unhead/schema` package is now deprecated, and it is recommended to import types from `unhead/types` instead.  
This PR updates the type imports accordingly.
https://unhead-unjs-io.nuxt.dev/docs/migration#deprecated-unheadschema
1. **Updated UseScriptContext type definition**
```ts
export type UseScriptContext<T extends Record<symbol | string, any>> = ScriptInstance<T>
```
- **Reference**: [unhead/src/scripts/types.ts#L13](https://github.com/unjs/unhead/blob/9d837c2217240f4e997cf18a25b79632ef8d6c24/packages/unhead/src/scripts/types.ts#L13)
2. **Converted ScriptBase to ScriptWithoutEvents**
```ts
type ScriptInput = ScriptWithoutEvents & DataKeys & …
```
=> fix: typecheck error

docs/content/scripts/tracking/google-tag-manager.md, src/runtime/components/ScriptGoogleMaps.vue, src/runtime/registry/google-maps.ts
Should resolve #336 
The useScriptGoogleMaps composable has had parameters for region and language added on #286 but the component was not passing the required prop to the composable so we could not set the region, language or version parameters on the component.
We can now set these parameters on the component as per the following example:
```
<ScriptGoogleMaps ref="maps" :mapOptions="{ region: 'PT', language: 'PT', v: '3.59' }"/>
```
Also, the version parameter previously only allowed values weekly, alpha and beta. This adds "quarterly" or specific version string.  (See https://developers.google.com/maps/documentation/javascript/versions)
Also fixed a link and markdown syntax issue on the documentation page about the Google Tag Manager
Cheers 👍
=> fix(googleMaps): configurable google map options

src/runtime/components/ScriptGoogleMaps.vue
On my previous PR I had added these params inside mapOptions which turns out is not correct since that maps to [google.maps.mapOptions](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions). (sorry 😩)
They're separate props now.
=> fix(googleMaps): region, language and version be own props

src/runtime/components/ScriptGoogleMaps.vue
Center marker always shown on maps placeholder image, no matter the value of `center-marker` prop
Resolves #402 
Center marker was always shown on maps placeholder image, no matter the value of `center-marker` prop.
=> fix: center marker always shown on maps placeholder image #402

docs/content/scripts/analytics/rybbit-analytics.md, src/registry.ts, src/runtime/registry/rybbit-analytics.ts, src/runtime/types.ts
Add [Rybbit Analytics](https://www.rybbit.io/) to registry
=> feat: add rybbit analytics to registry

docs/app/pages/[...slug].vue
🔗 Linked issue
Resolve: https://github.com/nuxt/scripts/issues/452
❓ Type of change
- [] ✨ New feature (a non-breaking change that adds functionality)
- [] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
📚 Description
Currently the Introduction page missing the next links to navigate between pages. This fix add it manually only on the page needed.
=> docs: add manual ContentSurround for the introduction step

src/runtime/components/ScriptGoogleMaps.vue
This is a follow-up to my previous fix related to the centerMarkers #402 #454 
This PR addresses another issue with the `centerMarker` prop in the Google Maps component:
**Fixed center marker removal bug**: The marker removal logic was incorrectly protecting center markers from deletion regardless of the `centerMarker` prop state, causing center markers to persist even when disabled
**Added explicit default value**: Set `centerMarker: true` in props defaults to make the component's behavior predictable and consistent with its implicit logic
=> fix: properly handle centerMarker removal logic

docs/content/scripts/tracking/meta-pixel.md, src/runtime/registry/meta-pixel.ts
This PR refactors the Meta Pixel (fbq) integration to improve type safety and developer experience.
- Adds explicit types for each valid fbq call pattern
- Adds support for additional Meta Pixel call patterns
- trackSingle
- trackSingleCustom
- consent
- Adds a fallback [string, ...any[]] signature at the end to preserve compatibility with undocumented or custom usages
- Makes contents in EventObjectProperties optional to prevent type errors in common usage
- Updates documentation to reflect the new types
https://developers.facebook.com/docs/meta-pixel/advanced
https://developers.facebook.com/docs/meta-pixel/implementation/gdpr/
=> fix(meta-pixel): refine fbq type definitions

src/plugins/transform.ts, test/e2e/cdn.test.ts, test/fixtures/cdn/app.vue, test/fixtures/cdn/nuxt.config.ts, test/unit/transform.test.ts
https://github.com/nuxt/scripts/issues/469
=> fix: support cdnURL for bundled scripts

docs/app/components/Footer.vue
No issue. Just a quick fix.
This PR fixes the broken links on the footer.
I can push a couple more commits adding `better-sqlite3` (required by `@nuxt/content` since one of their last versions) and deduping dependencies from the lockfile.
I didn't just in case you'd rather do that yourself or in case doing so would affect something in the current setup.
=> doc: fix broken footer links

docs/content/scripts/analytics/databuddy-analytics.md, src/registry.ts, src/runtime/registry/databuddy-analytics.ts
This pull request adds support for the Databuddy Analytics integration to the scripts registry, including a new composable for Nuxt apps, schema validation, and full documentation. The main changes are the addition of the registry entry, implementation of the integration logic, and comprehensive usage docs.
**Databuddy Analytics Integration**
* Added a new registry entry for Databuddy Analytics in the scripts registry, including label, category, logo, and import path for the composable.
* Implemented the `useScriptDatabuddyAnalytics` composable in `databuddy-analytics.ts`, providing schema validation, script injection, and a typed API for interacting with [Databuddy Analytics](https://www.databuddy.cc/).
**Documentation**
* Added a new documentation page at …
=> feat: add databuddy analytics

docs/app/assets/css/main.css, docs/app/components/Header.vue, docs/app/layouts/docs.vue, docs/app/pages/index.vue, docs/nuxt.config.ts, docs/package.json, pnpm-lock.yaml
Resolves #504 
This pull request upgrades the documentation site from `@nuxt/ui-pro` to the new `@nuxt/ui` v4 alpha and updates related dependencies and code to match the new UI library. It also refactors several components to use updated UI primitives and navigation logic, and synchronizes the lockfile with new package versions.
**UI Library Migration**
* Migrated from `@nuxt/ui-pro` to `@nuxt/ui@4.0.0-alpha.2` across the codebase (`docs/package.json`, `docs/nuxt.config.ts`, `docs/app/assets/css/main.css`, `pnpm-lock.yaml`). 
**Component Refactoring for New UI**
* Refactored `Header.vue` to use the new navigation injection, route-based navigation logic, and `UNavigationMenu`/`UContentNavigation` components for improved navigation structure. 
* Updated `docs.vue` layout to use new …
=> docs: improve responsiveness

src/runtime/registry/stripe.ts
"Resolves #508 " 
This pull request updates the url and type of the exposed stripe instance by the composable, when i followed the guide to implement stripe with nuxt/scripts i detected typescript errors that shouldnt be there, the reason was that the previous versions of stripe's library used to expose the constructor as Stripe, however in the newer versions the type is called StripeConstructor.
The reason im marking it as a breaking change is the fact that stripes api has changed considerably with the newer version, and updating nuxt/scripts would automatically update the library which can cause implementation problems because of the deprecated functions and such.
If this being a breaking change is a problem i can also implement a different script for the newer version of stripe. and …
=> feat(stripe)!: Stripe basil

docs/content/docs/1.guides/2.bundling.md, test/unit/transform.test.ts
#466
Make it clearer that bundling requires static script src.
=> docs: improve bundling documentation

docs/content/docs/1.guides/1.script-triggers.md, docs/content/docs/3.api/3.use-script-trigger-idle-timeout.md, docs/content/docs/3.api/3.use-script-trigger-interaction.md, src/runtime/composables/useScriptTriggerIdleTimeout.ts, src/runtime/composables/useScriptTriggerInteraction.ts, src/runtime/types.ts, src/templates.ts, test/unit/templates.test.ts
#467
Allows us to register global / registry scripts that have more granular triggers from nuxt.config.
**Load GA after 1 second idle timeout**
```ts
export default defineNuxtConfig({
scripts: {
registry: {
googleAnalytics: [{
id: 'GA_MEASUREMENT_ID'
}, {
trigger: { idleTimeout: 1000 }
}]
}
}
})
```
**Load a chat widget only on interaction**
```ts
export default defineNuxtConfig({
scripts: {
globals: {
chatWidget: ['https://widget.example.com/chat.js', {
trigger: { interaction: ['scroll', 'click', 'touchstart'] }
}]
}
}
})
```
=> feat: new event triggers

src/runtime/components/GoogleMaps/ScriptGoogleMapsMarker.vue, src/runtime/components/GoogleMaps/ScriptGoogleMapsMarkerClusterer.vue
We should not only optimize the removal of markers from marker clusterer, but also their addition! Adding hundreds of markers without this change causes a significant delay.
=> perf(googleMaps): avoid multiple rerenders when adding markers to clusterer

src/runtime/registry/google-tag-manager.ts
Global gtag function not exposed when using GTM via useScriptGoogleTagManager (https://github.com/nuxt/scripts/issues/523)
Expose globally the gtag function on the Google Tag Manager Script, useful for consent updates.
=> fix(gtm): expose `gtag` globally
