- src/runtime/types.ts
Hey :wave: 
this PR move the content of `RegistryScripts` to `RegistryScript`
> chore: add RegistryScript type

- docs/pages/index.vue
> docs: fix homepage css

- docs/pages/index.vue
> docs: fix homepage `ButtonGroup` mobile rounded border

- client/package.json
- docs/package.json
- pnpm-lock.yaml
It's about package management that I was talking about in this comment.
- https://github.com/nuxt/scripts/pull/93#discussion_r1639117932
- https://github.com/nuxt/scripts/pull/93#issuecomment-2167074889
In this PR, I did the following two things:
1. Combined the overlapping parts between root and `clinet/package.json` into root
2. Deleted `Nuxt` from `docs/` (to use the version managed by root)
> chore(monorepo): update deps in `client/`

- .github/pull_request_template.md
Chcklists were note used much in other repo either. So I deleted it.
> chore(template): fix PR template

- package.json
- pnpm-lock.yaml
- src/runtime/registry/vimeo-player.ts
#92
package update with a build fix
> chore: update nuxt-module-builder to 0.8.0

- docs/content/docs/1.getting-started/5.contributing.md
#69 
add a very basic contribution guide
> docs: add basic contribution guide

- docs/content/scripts/analytics/matomo-analytics.md
- fix external link to matomo website
> fix(docs): matomo-analytics website url

- docs/content/docs/1.getting-started/5.contributing.md
related #69, #109, #120
fixed a contribution guide along with the removal of the `postinstall` command.
> docs: fix contributing guide

- docs/components/content/IntercomDemo.vue
- docs/components/content/LemonSqueezyDemo.vue
- docs/content/scripts/payments/lemon-squeezy.md
- playground/pages/third-parties/lemon-squeezy.vue
- playground/pages/third-parties/lemon-squeezy/component.vue
- playground/pages/third-parties/lemon-squeezy/script.vue
- src/runtime/components/ScriptLemonSqueezy.vue
- src/runtime/registry/lemon-squeezy.ts
https://github.com/nuxt/scripts/issues/98
https://github.com/nuxt/scripts/issues/41
The `ScriptLemonSqueezy` component replaces `ScriptLemonSqueezyButton`.
This new version provides simpler usage and ensures that buttons always resolve to open the modal.
Usage
```vue
<template>
<ScriptLemonSqueezy>
<NuxtLink href="https://harlantest.lemonsqueezy.com/buy/52a40427-36d2-4450-a514-ae80d9e1a333?embed=1">
Buy me - $9.99
</NuxtLink>
</ScriptLemonSqueezy>
</template>
```
> feat!: `ScriptLemonSqueezy`

- src/tpc/utils.ts
fix #133
This PR adds a type annotation for tpc composables
> fix(tpc): annotate return type of tpc composables

- src/registry.ts
> fix: fix google analytics category

- docs/content/scripts/analytics/plausible-analytics.md
Fix typo in environment variable NUXT_PUBLIC_SCRIPTS_PLAUSIBLE_ANALYTICS_DOMAIN
- [x ] 📖 Documentation (updates to the documentation or readme)
> docs: fix typo in plausible analytics env var example

- docs/content/scripts/content/google-maps.md
The API also needs access to Places API, otherwise it throws an error when loading the map on hover. I added this info to the docs.
> docs(GoogleMaps): Added Places API to requirements of API key

- src/registry.ts
> fix: use correct google analytics logo

- .github/ISSUE_TEMPLATE/config.yml
related this commit: 669ed2a01ebd9fe206fcb7fc27c0b44da5ad8deb
We've added a documentation link to config.yml.
So you can review the documentation before opening an issue.
> chore(ci): add docs link in Issue template

- docs/content/docs/1.getting-started/2.installation.md
Fixes a few broken links in the "next steps" section.
> docs: Fix broken links

- docs/pages/index.vue
> docs: fix broken link

- docs/content/scripts/analytics/plausible-analytics.md
>  docs: add coding group end to plausible page

- client/package.json
- package.json
- pnpm-lock.yaml
- src/devtools.ts
resolves https://github.com/nuxt/ecosystem-ci/actions/runs/10553843377/job/29254385373
This updates nuxt + removes a `@ts-expect-error` to make ecoystem-ci pass...
> chore: bump nuxt version

- src/runtime/composables/useScript.ts
Typo in https://github.com/nuxt/scripts/commit/510d7b9c243cf57734bb4ad6374eaf27fe701741
> fix: do not omit `crossorigin` from link preload

- docs/content/scripts/analytics/plausible-analytics.md
Fix typo in doc
- [x ] 📖 Documentation (updates to the documentation or readme)
> doc: plausible-analytics.md

- src/assets.ts
https://github.com/nuxt/scripts/issues/233
This PR await for all download to be finished before verifying if there's any scripts that failed. This is a DX improvement to avoid having users debugging scripts one by one when there's multiple urls failing
> fix: group failed scripts log

- docs/content/scripts/content/youtube-player.md
Changed a typo in the YouTube Player Script Registry (before war referenced as "Vimeo Video")
> docs: :pencil2: Updated definition for YouTube Player

- docs/pages/index.vue
A sentence in the homepage of the docs reads like it's missing something.
I'm not sure if my fix is wanted or if it goes in the right way, feel free to close or suggest other edits
> docs: fix typo/incomplete sentence

- src/runtime/registry/google-maps.ts
The Google Maps script supports optional params to force the language and region of the maps/results [see documentation](https://developers.google.com/maps/documentation/javascript/localization). This PR adds support for it.
> feat(googleMaps): language & region params

- README.md
> doc: broken README links

- .github/workflows/ci.yml
This PR removes corepack from the ci since we can't use any pnpm with corepack right now
> ci: remove corepack

- docs/content/scripts/analytics/umami-analytics.md
Not actually wrong, but I think its prettier if plausible is not mentioned on umami page
> docs: wrong variable name

- docs/content/docs/1.guides/0.key-concepts.md
Link to defaultScriptOptions API option ends up in a 404.
> doc: use absolute link for defaultScriptOptions

- src/runtime/components/ScriptYouTubePlayer.vue
> fix(ScriptYouTubePlayer) : show iframe

- src/runtime/components/ScriptGoogleMaps.vue
- src/runtime/registry/google-maps.ts
This PR fixes the type augmentation for useScritpGoogleMaps
> fix(googleMaps): fix window type augmentation

- package.json
> build: add missing externals

- docs/content/scripts/tracking/x-pixel.md
N/A
There was a mistake in the documentation regarding XPixelAPI, which has been corrected based on [the current implementation](https://github.com/nuxt/scripts/blob/v0.11.8/src/runtime/registry/x-pixel.ts).
> docs: correct contents of XPixelAPI
